Repository LabDevs/SmallTalk, pull requests merged in 2020-05, with the labels that each got.

#50 React 40
  client/src/App.js
  client/src/components/Login.jsx
  client/src/components/UpdateEvent.jsx
  controllers/user.js
  middleware/authenticate.js
Labels: front-end

#62 added unit testing for App , Login and Register Component
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/App.test.js
  client/src/components/AddEvent.jsx
  client/src/test/App.test.js
  client/src/test/Login.test.js
  client/src/test/Register.test.js
Labels: testing

#65 React-61
  app.js
  client/src/App.js
  client/src/components/AddEvent.jsx
  client/src/components/CategoriesEventList.jsx
  client/src/components/DashBoard.jsx
  client/src/components/DashBoardEvent.jsx
  client/src/components/UpcomingEvents.jsx
  client/src/components/UpdateEvent.jsx
  client/src/test/App.test.js
  client/src/test/Register.test.js
  controllers/rsvp.js
Labels: front-end

#74 bug-67
  client/src/App.js
  client/src/components/DashBoard.jsx
  client/src/components/Home.jsx
  client/src/components/Login.jsx
  client/src/components/Register.jsx
  client/src/components/UpcomingEvents.jsx
  controllers/rsvp.js
  controllers/user.js
  models/Category.js
Labels: bug

#84 added to the event card
  client/src/App.js
  client/src/components/DashBoard.jsx
  client/src/components/DashBoardEvent.jsx
  controllers/user.js
  seeds/rsvp_data.js
Labels: back-end, front-end

#88 Video feature
  app.js
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/components/Login.jsx
  client/src/components/VideoChat.jsx
  package-lock.json
  package.json
  seeds/events_data.js
  seeds/rsvp_data.js
Labels: back-end

#95 Adds more styling to components, fixes some bugs, adds some new UX
  client/src/App.js
  client/src/components/AddEvent.jsx
  client/src/components/DashBoard.jsx
  client/src/components/DashBoardEvent.jsx
  client/src/components/Login.jsx
  client/src/components/Register.jsx
  client/src/components/UpcomingEvents.jsx
  client/src/components/UpdateEvent.jsx
  client/src/index.css
  controllers/category.js
  controllers/user.js
  middleware/authenticate.js
  models/Category.js
  routes/category.js
  seeds/04_rsvp_seed.js
Labels: front-end

#112 Video Room
  app.js
  client/src/App.js
  client/src/components/CategoryCard.js
  client/src/components/CategoryEvent.jsx
  client/src/components/CategoryPage.jsx
  client/src/components/DashBoard.jsx
  client/src/components/DashBoardEvent.jsx
  client/src/components/UpcomingEvents.jsx
  client/src/components/UpcomingEventsCard.jsx
  client/src/components/VideoChat.jsx
  client/src/components/VideoChatTwo.jsx
  client/src/contexts/UserContext.jsx
  client/src/contexts/UserContextProvider.jsx
  controllers/user.js
  models/Category.js
  models/User.js
  routes/category.js
Labels: back-end, front-end
